# use this for multiple zshrc files
# find a better way to do this
[[ -r ~/.zshrc-secret ]] && . ~/.zshrc-secret
[[ -r ~/.zshrc-linux ]] && . ~/.zshrc-linux
[[ -r ~/.zshrc-osx ]] && . ~/.zshrc-osx

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="terminalparty-root"
#ZSH_THEME="terminalparty"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#
# Plugins are set in os specific zshrc
#
#plugins=(archlinux debian django git heroku history-substring-search jira node pip reddit rvm screen tmux vi-mode virtualenvwrapper vundle web-search)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
setopt CORRECT

alias t='/usr/local/bin/todo.sh'
#alias splunk-pwd='export SPLUNK_HOME=`pwd`'
alias pycd='cdpy'
cdpy() { cd ~/code/py/"$*"; } 
_cdpy() {
	_files -W ~/code/py/
}
compdef _cdpy cdpy
#spl() { cd /opt/splunk/"$*"; } 
#_spl() {
#	_files -W /opt/splunk/
#}
#compdef _spl spl
